#!/usr/bin/env bash
# Validates commit message format against project conventions.
# Called by lefthook commit-msg hook. Receives the commit message file path as $1.
#
# Rules:
#   - First line must match: type(scope): lowercase description
#   - Allowed types: feat, fix, refactor, docs, test, chore
#   - First line max 72 characters
#   - No AI attribution anywhere in the message

set -euo pipefail

COMMIT_MSG_FILE="$1"
FIRST_LINE=$(head -n1 "$COMMIT_MSG_FILE")

# --- Format check ---
FORMAT_REGEX='^(feat|fix|refactor|docs|test|chore)\([a-z][a-z0-9-]*\): [a-z].*$'

if ! echo "$FIRST_LINE" | grep -qE "$FORMAT_REGEX"; then
  echo ""
  echo "ERROR: Invalid commit message format."
  echo ""
  echo "  Got:      $FIRST_LINE"
  echo "  Expected: type(scope): lowercase description"
  echo ""
  echo "  Allowed types:  feat, fix, refactor, docs, test, chore"
  echo "  Scope:          lowercase alphanumeric + hyphens (e.g. client, mono, ui)"
  echo "  Description:    must start with a lowercase letter"
  echo ""
  echo "  Examples:"
  echo "    feat(client): add team pulse dashboard"
  echo "    fix(core): handle null in result type"
  echo "    chore(mono): update lefthook config"
  echo ""
  exit 1
fi

# --- Length check ---
LINE_LENGTH=${#FIRST_LINE}
if [ "$LINE_LENGTH" -gt 72 ]; then
  echo ""
  echo "ERROR: Commit message first line is too long ($LINE_LENGTH chars, max 72)."
  echo ""
  echo "  Got: $FIRST_LINE"
  echo ""
  exit 1
fi

# --- AI attribution check ---
if grep -qiE '(co-authored-by|powered by|generated by|assisted by):?\s*(claude|anthropic|copilot|chatgpt|openai)' "$COMMIT_MSG_FILE"; then
  echo ""
  echo "ERROR: Commit message contains AI attribution."
  echo ""
  echo "  This project does not allow AI attribution in commits."
  echo "  Remove any Co-Authored-By, Powered by, or Generated by lines"
  echo "  that reference AI tools."
  echo ""
  exit 1
fi

exit 0
